/* Ce Voyage — Multilingual content: en, fr, ru, tr, de, ar */
window.I18N = {
  en: {
    navDiscover: "Discover",
    navRegions: "Regions",
    navExperiences: "Experiences",
    navMap: "Map",
    navGuide: "Travel Guide",
    navContact: "Contact",
    heroEyebrow: "The island of a thousand journeys",
    heroTitleOne: "Discover Sri Lanka,",
    heroTitleTwo: "beyond the ordinary.",
    heroText: "Explore ancient cities, misty mountains, wild coastlines, sacred places and local stories through one beautiful travel information centre.",
    searchButton: "Explore",
    searchPlaceholder: "Search places, regions or experiences...",
    popularLabel: "Popular:",
    wildlife: "Wildlife",
    provinces: "Provinces",
    heritage: "Heritage",
    introKicker: "A living island",
    introTitle: "One destination.<br/><em>Endless stories.</em>",
    introText: "From the ancient kingdoms of the Cultural Triangle to the tea-covered hills, tropical beaches and wildlife-rich forests, Sri Lanka offers extraordinary variety within one island.",
    exploreRegions: "Explore all regions",
    featuredKicker: "Editor's collection",
    featuredTitle: "Places worth the journey",
    hillCountry: "Hill Country",
    coastalHeritage: "Coastal Heritage",
    wildNature: "Wild Nature",
    sigiriyaDesc: "Ancient rock fortress, royal gardens and unforgettable views.",
    ellaDesc: "Tea trails, mountain air and one of Asia's most scenic rail journeys.",
    galleDesc: "Ocean walls, colonial streets and timeless southern charm.",
    yalaDesc: "Leopards, elephants and dramatic landscapes between forest and sea.",
    regionsKicker: "Explore geographically",
    regionsTitle: "Find your region",
    all: "All",
    culture: "Culture",
    nature: "Nature",
    coast: "Coast",
    centralProvince: "Central Province",
    centralDesc: "Sacred Kandy, misty highlands and ancient cave temples.",
    southernProvince: "Southern Province",
    southernDesc: "Historic Galle, surf towns, whale country and golden beaches.",
    uvaProvince: "Uva Province",
    uvaDesc: "Mountain viewpoints, waterfalls, tea estates and quiet villages.",
    northCentralProvince: "North Central Province",
    northCentralDesc: "The heartland of Sri Lanka's ancient royal civilisation.",
    easternProvince: "Eastern Province",
    easternDesc: "Calm bays, coral seas, temples and laid-back coastal life.",
    sabaragamuwaProvince: "Sabaragamuwa Province",
    sabaragamuwaDesc: "Rainforests, sacred peaks, rivers and Sri Lanka's gem country.",
    experienceKicker: "Travel by feeling",
    experienceTitle: "Choose the experience that calls you.",
    ancientHeritage: "Ancient Heritage",
    wildlifeSafaris: "Wildlife & Safaris",
    beaches: "Beaches & Islands",
    adventure: "Adventure & Outdoors",
    wellness: "Wellness & Ayurveda",
    food: "Food & Local Life",
    mapKicker: "Explore visually",
    mapTitle: "Sri Lanka at a glance",
    mapText: "Select a marker to discover signature destinations across the island.",
    guideKicker: "Know before you go",
    guideTitle: "Practical travel knowledge, beautifully simple.",
    weatherTitle: "Weather & Seasons",
    weatherText: "Understand Sri Lanka's regional monsoons and the best months for each coast.",
    transportTitle: "Getting Around",
    transportText: "Learn about trains, buses, private transport and realistic travel times.",
    cultureTitle: "Culture & Etiquette",
    cultureText: "Travel respectfully with simple guidance for temples, communities and local customs.",
    readGuide: "Read guide →",
    contactKicker: "Contact us",
    osReady: "Ready for Travel OS",
    contactTitle: "Your link to Sri Lanka, from France.",
    contactIntro: "For any information about destinations, experiences and tourism services in Sri Lanka, contact our team.",
    openWhatsApp: "Open WhatsApp France",
    addressTitle: "Address in France",
    whatsappPrimary: "Primary WhatsApp — France",
    phoneSriLanka: "Phone / WhatsApp Sri Lanka",
    emailLabel: "Email",
    websiteLabel: "Website",
    requestKicker: "Your travel project",
    requestTitle: "Tell us about your next journey.",
    requestText: "This form is ready to connect to your future Travel OS. For now, it opens WhatsApp with your request.",
    fullNameLabel: "Full name",
    fullNamePlaceholder: "Your full name",
    emailFormLabel: "Email",
    emailFormPlaceholder: "your@email.com",
    whatsappFormLabel: "Phone / WhatsApp",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "Travel date",
    travellersLabel: "Number of travellers",
    interestLabel: "Main experience",
    interestTour: "Cultural circuit",
    interestNature: "Nature & wildlife",
    interestBeach: "Beaches",
    interestFamily: "Family trip",
    interestCustom: "Tailor-made journey",
    messageLabel: "Your request",
    messagePlaceholder: "Describe your travel idea...",
    sendRequest: "Send request",
    newsletterKicker: "Stories from the island",
    newsletterTitle: "Let Sri Lanka inspire your next journey.",
    newsletterText: "Receive destination stories, seasonal travel ideas and new hidden-place guides.",
    emailPlaceholder: "Your email address",
    subscribe: "Subscribe",
    footerText: "A premium information centre for discovering the people, places and experiences of Sri Lanka.",
    explore: "Explore",
    destinations: "Destinations",
    experiences: "Experiences",
    interactiveMap: "Interactive Map",
    travelInfo: "Travel Info",
    weather: "Weather",
    transport: "Transport",
    safety: "Safety & Etiquette",
    languages: "Languages",
    informationalOnly: "Informational travel platform — no direct booking.",
    whatsappFrance: "WhatsApp France",
    noResults: "No results found",
    openingWhatsApp: "Opening WhatsApp...",
    waToast: "WhatsApp is opening with your request",
    thanksSubscribe: "Thank you! We'll send you inspiration soon.",
    subSaved: "Subscription saved",
    langName: "English",
  },
  fr: {
    navDiscover: "Découvrir",
    navRegions: "Régions",
    navExperiences: "Expériences",
    navMap: "Carte",
    navGuide: "Guide de voyage",
    navContact: "Contact",
    heroEyebrow: "L'île aux mille voyages",
    heroTitleOne: "Découvrez le Sri Lanka,",
    heroTitleTwo: "au-delà de l'ordinaire.",
    heroText: "Explorez les cités anciennes, les montagnes brumeuses, les côtes sauvages, les lieux sacrés et les histoires locales à travers un beau centre d'information voyage.",
    searchButton: "Explorer",
    searchPlaceholder: "Rechercher lieux, régions ou expériences...",
    popularLabel: "Populaire :",
    wildlife: "Faune",
    provinces: "Provinces",
    heritage: "Patrimoine",
    introKicker: "Une île vivante",
    introTitle: "Une destination.<br/><em>Des histoires infinies.</em>",
    introText: "Des anciens royaumes du Triangle Culturel aux collines de thé, plages tropicales et forêts riches en faune, le Sri Lanka offre une variété extraordinaire sur une seule île.",
    exploreRegions: "Explorer toutes les régions",
    featuredKicker: "Sélection de la rédaction",
    featuredTitle: "Des lieux qui valent le voyage",
    hillCountry: "Pays des collines",
    coastalHeritage: "Patrimoine côtier",
    wildNature: "Nature sauvage",
    sigiriyaDesc: "Forteresse rocheuse antique, jardins royaux et vues inoubliables.",
    ellaDesc: "Sentiers de thé, air de montagne et l'un des plus beaux trajets ferroviaires d'Asie.",
    galleDesc: "Remparts face à l'océan, rues coloniales et charme intemporel du Sud.",
    yalaDesc: "Léopards, éléphants et paysages dramatiques entre forêt et mer.",
    regionsKicker: "Explorer géographiquement",
    regionsTitle: "Trouvez votre région",
    all: "Tout",
    culture: "Culture",
    nature: "Nature",
    coast: "Côte",
    centralProvince: "Province Centrale",
    centralDesc: "Kandy sacrée, hauts plateaux brumeux et temples rupestres anciens.",
    southernProvince: "Province du Sud",
    southernDesc: "Galle historique, villes de surf, pays des baleines et plages dorées.",
    uvaProvince: "Province d'Uva",
    uvaDesc: "Points de vue montagneux, cascades, plantations de thé et villages tranquilles.",
    northCentralProvince: "Province du Centre-Nord",
    northCentralDesc: "Le cœur de la civilisation royale antique du Sri Lanka.",
    easternProvince: "Province de l'Est",
    easternDesc: "Baies calmes, mers de corail, temples et vie côtière détendue.",
    sabaragamuwaProvince: "Province de Sabaragamuwa",
    sabaragamuwaDesc: "Forêts tropicales, sommets sacrés, rivières et pays des gemmes.",
    experienceKicker: "Voyager selon le ressenti",
    experienceTitle: "Choisissez l'expérience qui vous appelle.",
    ancientHeritage: "Patrimoine antique",
    wildlifeSafaris: "Faune & Safaris",
    beaches: "Plages & Îles",
    adventure: "Aventure & Plein air",
    wellness: "Bien-être & Ayurveda",
    food: "Cuisine & Vie locale",
    mapKicker: "Explorer visuellement",
    mapTitle: "Le Sri Lanka en un coup d'œil",
    mapText: "Sélectionnez un marqueur pour découvrir les destinations signature de l'île.",
    guideKicker: "À savoir avant de partir",
    guideTitle: "Des connaissances pratiques, joliment simples.",
    weatherTitle: "Météo & Saisons",
    weatherText: "Comprenez les moussons régionales du Sri Lanka et les meilleurs mois pour chaque côte.",
    transportTitle: "Se déplacer",
    transportText: "Trains, bus, transport privé et temps de trajet réalistes.",
    cultureTitle: "Culture & Étiquette",
    cultureText: "Voyagez respectueusement avec des conseils simples pour temples, communautés et coutumes.",
    readGuide: "Lire le guide →",
    contactKicker: "Nous contacter",
    osReady: "Prêt pour Travel OS",
    contactTitle: "Votre lien avec le Sri Lanka, depuis la France.",
    contactIntro: "Pour toute demande d'information sur les destinations, les expériences et les services touristiques au Sri Lanka, contactez notre équipe.",
    openWhatsApp: "Ouvrir WhatsApp France",
    addressTitle: "Adresse en France",
    whatsappPrimary: "WhatsApp principal — France",
    phoneSriLanka: "Téléphone / WhatsApp Sri Lanka",
    emailLabel: "E-mail",
    websiteLabel: "Site Web",
    requestKicker: "Votre projet de voyage",
    requestTitle: "Parlez-nous de votre prochain voyage.",
    requestText: "Ce formulaire est déjà préparé pour être connecté à votre futur Travel OS. Pour le moment, il ouvre WhatsApp avec votre demande.",
    fullNameLabel: "Nom complet",
    fullNamePlaceholder: "Votre nom complet",
    emailFormLabel: "E-mail",
    emailFormPlaceholder: "votre@email.com",
    whatsappFormLabel: "Téléphone / WhatsApp",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "Date de voyage",
    travellersLabel: "Nombre de voyageurs",
    interestLabel: "Expérience principale",
    interestTour: "Circuit culturel",
    interestNature: "Nature et faune",
    interestBeach: "Plages",
    interestFamily: "Voyage en famille",
    interestCustom: "Voyage sur mesure",
    messageLabel: "Votre demande",
    messagePlaceholder: "Décrivez votre idée de voyage...",
    sendRequest: "Envoyer la demande",
    newsletterKicker: "Histoires de l'île",
    newsletterTitle: "Laissez le Sri Lanka inspirer votre prochain voyage.",
    newsletterText: "Recevez des histoires de destinations, des idées saisonnières et de nouveaux guides de lieux cachés.",
    emailPlaceholder: "Votre adresse e-mail",
    subscribe: "S'abonner",
    footerText: "Un centre d'information premium pour découvrir les gens, les lieux et les expériences du Sri Lanka.",
    explore: "Explorer",
    destinations: "Destinations",
    experiences: "Expériences",
    interactiveMap: "Carte interactive",
    travelInfo: "Infos voyage",
    weather: "Météo",
    transport: "Transport",
    safety: "Sécurité & Étiquette",
    languages: "Langues",
    informationalOnly: "Plateforme d'information voyage — pas de réservation directe.",
    whatsappFrance: "WhatsApp France",
    noResults: "Aucun résultat trouvé",
    openingWhatsApp: "Ouverture de WhatsApp...",
    waToast: "WhatsApp s'ouvre avec votre demande",
    thanksSubscribe: "Merci ! Nous vous enverrons bientôt des inspirations.",
    subSaved: "Inscription enregistrée",
    langName: "Français",
  },
  ru: {
    navDiscover: "Открыть",
    navRegions: "Регионы",
    navExperiences: "Впечатления",
    navMap: "Карта",
    navGuide: "Путеводитель",
    navContact: "Контакты",
    heroEyebrow: "Остров тысячи путешествий",
    heroTitleOne: "Откройте Шри-Ланку,",
    heroTitleTwo: "за пределами обычного.",
    heroText: "Исследуйте древние города, туманные горы, дикие побережья, священные места и местные истории через один красивый туристический информационный центр.",
    searchButton: "Исследовать",
    searchPlaceholder: "Поиск мест, регионов или впечатлений...",
    popularLabel: "Популярное:",
    wildlife: "Живая природа",
    provinces: "Провинции",
    heritage: "Наследие",
    introKicker: "Живой остров",
    introTitle: "Одно направление.<br/><em>Бесконечные истории.</em>",
    introText: "От древних королевств Культурного треугольника до чайных холмов, тропических пляжей и богатых дикой природой лесов — Шри-Ланка предлагает необычайное разнообразие на одном острове.",
    exploreRegions: "Все регионы",
    featuredKicker: "Выбор редакции",
    featuredTitle: "Места, ради которых стоит ехать",
    hillCountry: "Горная страна",
    coastalHeritage: "Прибрежное наследие",
    wildNature: "Дикая природа",
    sigiriyaDesc: "Древняя скальная крепость, королевские сады и незабываемые виды.",
    ellaDesc: "Чайные тропы, горный воздух и один из самых живописных железнодорожных маршрутов Азии.",
    galleDesc: "Океанские стены, колониальные улицы и вечная прелесть юга.",
    yalaDesc: "Леопарды, слоны и драматические пейзажи между лесом и морем.",
    regionsKicker: "Исследовать географически",
    regionsTitle: "Найдите свой регион",
    all: "Все",
    culture: "Культура",
    nature: "Природа",
    coast: "Побережье",
    centralProvince: "Центральная провинция",
    centralDesc: "Священный Канди, туманные высокогорья и древние пещерные храмы.",
    southernProvince: "Южная провинция",
    southernDesc: "Исторический Галле, сёрф-города, киты и золотые пляжи.",
    uvaProvince: "Провинция Ува",
    uvaDesc: "Горные смотровые площадки, водопады, чайные плантации и тихие деревни.",
    northCentralProvince: "Северо-Центральная провинция",
    northCentralDesc: "Сердце древней королевской цивилизации Шри-Ланки.",
    easternProvince: "Восточная провинция",
    easternDesc: "Спокойные бухты, коралловые моря, храмы и неспешная прибрежная жизнь.",
    sabaragamuwaProvince: "Провинция Сабарагамува",
    sabaragamuwaDesc: "Тропические леса, священные вершины, реки и страна драгоценных камней.",
    experienceKicker: "Путешествие по ощущениям",
    experienceTitle: "Выберите опыт, который вас зовёт.",
    ancientHeritage: "Древнее наследие",
    wildlifeSafaris: "Сафари и природа",
    beaches: "Пляжи и острова",
    adventure: "Приключения",
    wellness: "Велнес и аюрведа",
    food: "Еда и местная жизнь",
    mapKicker: "Исследовать визуально",
    mapTitle: "Шри-Ланка с одного взгляда",
    mapText: "Выберите метку, чтобы открыть знаковые места острова.",
    guideKicker: "Перед поездкой",
    guideTitle: "Практические знания — просто и красиво.",
    weatherTitle: "Погода и сезоны",
    weatherText: "Поймите региональные муссоны Шри-Ланки и лучшие месяцы для каждого побережья.",
    transportTitle: "Как передвигаться",
    transportText: "Поезда, автобусы, частный транспорт и реальное время в пути.",
    cultureTitle: "Культура и этикет",
    cultureText: "Путешествуйте уважительно: простые советы по храмам, общинам и обычаям.",
    readGuide: "Читать гид →",
    contactKicker: "Связаться с нами",
    osReady: "Готово к Travel OS",
    contactTitle: "Ваша связь со Шри-Ланкой из Франции.",
    contactIntro: "По любым вопросам о направлениях, впечатлениях и туристических услугах на Шри-Ланке — свяжитесь с нашей командой.",
    openWhatsApp: "Открыть WhatsApp Франция",
    addressTitle: "Адрес во Франции",
    whatsappPrimary: "Основной WhatsApp — Франция",
    phoneSriLanka: "Телефон / WhatsApp Шри-Ланка",
    emailLabel: "Эл. почта",
    websiteLabel: "Сайт",
    requestKicker: "Ваш проект поездки",
    requestTitle: "Расскажите о следующем путешествии.",
    requestText: "Форма готова к подключению к будущему Travel OS. Сейчас она открывает WhatsApp с вашим запросом.",
    fullNameLabel: "Полное имя",
    fullNamePlaceholder: "Ваше полное имя",
    emailFormLabel: "Эл. почта",
    emailFormPlaceholder: "your@email.com",
    whatsappFormLabel: "Телефон / WhatsApp",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "Дата поездки",
    travellersLabel: "Число путешественников",
    interestLabel: "Основной опыт",
    interestTour: "Культурный маршрут",
    interestNature: "Природа и фауна",
    interestBeach: "Пляжи",
    interestFamily: "Семейная поездка",
    interestCustom: "Индивидуальное путешествие",
    messageLabel: "Ваш запрос",
    messagePlaceholder: "Опишите идею поездки...",
    sendRequest: "Отправить запрос",
    newsletterKicker: "Истории с острова",
    newsletterTitle: "Пусть Шри-Ланка вдохновит следующее путешествие.",
    newsletterText: "Получайте истории мест, сезонные идеи и гиды по скрытым уголкам.",
    emailPlaceholder: "Ваш email",
    subscribe: "Подписаться",
    footerText: "Премиальный информационный центр о людях, местах и впечатлениях Шри-Ланки.",
    explore: "Исследовать",
    destinations: "Направления",
    experiences: "Впечатления",
    interactiveMap: "Интерактивная карта",
    travelInfo: "Информация",
    weather: "Погода",
    transport: "Транспорт",
    safety: "Безопасность и этикет",
    languages: "Языки",
    informationalOnly: "Информационная платформа — без прямого бронирования.",
    whatsappFrance: "WhatsApp Франция",
    noResults: "Ничего не найдено",
    openingWhatsApp: "Открытие WhatsApp...",
    waToast: "WhatsApp открывается с вашим запросом",
    thanksSubscribe: "Спасибо! Скоро пришлём вдохновение.",
    subSaved: "Подписка сохранена",
    langName: "Русский",
  },
  tr: {
    navDiscover: "Keşfet",
    navRegions: "Bölgeler",
    navExperiences: "Deneyimler",
    navMap: "Harita",
    navGuide: "Seyahat Rehberi",
    navContact: "İletişim",
    heroEyebrow: "Bin yolculuğun adası",
    heroTitleOne: "Sri Lanka'yı keşfedin,",
    heroTitleTwo: "sıradanın ötesinde.",
    heroText: "Antik şehirleri, sisli dağları, vahşi kıyıları, kutsal yerleri ve yerel hikâyeleri tek bir güzel seyahat bilgi merkezi üzerinden keşfedin.",
    searchButton: "Keşfet",
    searchPlaceholder: "Yer, bölge veya deneyim ara...",
    popularLabel: "Popüler:",
    wildlife: "Yaban hayatı",
    provinces: "İller",
    heritage: "Miras",
    introKicker: "Canlı bir ada",
    introTitle: "Tek destinasyon.<br/><em>Sonsuz hikâyeler.</em>",
    introText: "Kültürel Üçgen'in antik krallıklarından çay kaplı tepelere, tropikal plajlara ve yaban hayatı zengin ormanlara — Sri Lanka tek adada olağanüstü çeşitlilik sunar.",
    exploreRegions: "Tüm bölgeleri keşfet",
    featuredKicker: "Editörün seçimi",
    featuredTitle: "Yolculuğa değer yerler",
    hillCountry: "Dağlık bölge",
    coastalHeritage: "Kıyı mirası",
    wildNature: "Vahşi doğa",
    sigiriyaDesc: "Antik kaya kalesi, kraliyet bahçeleri ve unutulmaz manzaralar.",
    ellaDesc: "Çay patikaları, dağ havası ve Asya'nın en etkileyici tren yolculuklarından biri.",
    galleDesc: "Okyanus surları, sömürge sokakları ve zamansız güney cazibesi.",
    yalaDesc: "Leoparlar, filler ve orman ile deniz arasındaki dramatik manzaralar.",
    regionsKicker: "Coğrafi olarak keşfet",
    regionsTitle: "Bölgenizi bulun",
    all: "Tümü",
    culture: "Kültür",
    nature: "Doğa",
    coast: "Kıyı",
    centralProvince: "Merkez Bölge",
    centralDesc: "Kutsal Kandy, sisli yaylalar ve antik mağara tapınakları.",
    southernProvince: "Güney Bölge",
    southernDesc: "Tarihi Galle, sörf kasabaları, balina ülkesi ve altın plajlar.",
    uvaProvince: "Uva Bölgesi",
    uvaDesc: "Dağ manzaraları, şelaleler, çay çiftlikleri ve sakin köyler.",
    northCentralProvince: "Kuzey Merkez Bölge",
    northCentralDesc: "Sri Lanka'nın antik kraliyet medeniyetinin kalbi.",
    easternProvince: "Doğu Bölge",
    easternDesc: "Sakin koylar, mercan denizleri, tapınaklar ve rahat kıyı hayatı.",
    sabaragamuwaProvince: "Sabaragamuwa Bölgesi",
    sabaragamuwaDesc: "Yağmur ormanları, kutsal zirveler, nehirler ve değerli taş ülkesi.",
    experienceKicker: "Hisse göre seyahat",
    experienceTitle: "Sizi çağıran deneyimi seçin.",
    ancientHeritage: "Antik miras",
    wildlifeSafaris: "Yaban hayatı ve safari",
    beaches: "Plajlar ve adalar",
    adventure: "Macera ve doğa",
    wellness: "Wellness ve Ayurveda",
    food: "Yemek ve yerel yaşam",
    mapKicker: "Görsel olarak keşfet",
    mapTitle: "Bir bakışta Sri Lanka",
    mapText: "Adadaki imza destinasyonları keşfetmek için bir işaret seçin.",
    guideKicker: "Gitmeden önce bilin",
    guideTitle: "Pratik seyahat bilgisi, güzelce sade.",
    weatherTitle: "Hava ve mevsimler",
    weatherText: "Sri Lanka'nın bölgesel musonlarını ve her kıyı için en iyi ayları anlayın.",
    transportTitle: "Ulaşım",
    transportText: "Trenler, otobüsler, özel ulaşım ve gerçekçi seyahat süreleri.",
    cultureTitle: "Kültür ve görgü",
    cultureText: "Tapınaklar, topluluklar ve yerel gelenekler için saygılı seyahat rehberi.",
    readGuide: "Rehberi oku →",
    contactKicker: "Bize ulaşın",
    osReady: "Travel OS için hazır",
    contactTitle: "Fransa'dan Sri Lanka bağlantınız.",
    contactIntro: "Sri Lanka'daki destinasyonlar, deneyimler ve turizm hizmetleri hakkında bilgi için ekibimizle iletişime geçin.",
    openWhatsApp: "WhatsApp Fransa'yı aç",
    addressTitle: "Fransa adresi",
    whatsappPrimary: "Ana WhatsApp — Fransa",
    phoneSriLanka: "Telefon / WhatsApp Sri Lanka",
    emailLabel: "E-posta",
    websiteLabel: "Web sitesi",
    requestKicker: "Seyahat projeniz",
    requestTitle: "Bir sonraki yolculuğunuzu anlatın.",
    requestText: "Bu form gelecekteki Travel OS'e bağlanmaya hazır. Şimdilik talebinizle WhatsApp'ı açar.",
    fullNameLabel: "Ad soyad",
    fullNamePlaceholder: "Tam adınız",
    emailFormLabel: "E-posta",
    emailFormPlaceholder: "your@email.com",
    whatsappFormLabel: "Telefon / WhatsApp",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "Seyahat tarihi",
    travellersLabel: "Yolcu sayısı",
    interestLabel: "Ana deneyim",
    interestTour: "Kültür turu",
    interestNature: "Doğa ve yaban hayatı",
    interestBeach: "Plajlar",
    interestFamily: "Aile seyahati",
    interestCustom: "Özel tasarım yolculuk",
    messageLabel: "Talebiniz",
    messagePlaceholder: "Seyahat fikrinizi anlatın...",
    sendRequest: "Talebi gönder",
    newsletterKicker: "Adadan hikâyeler",
    newsletterTitle: "Sri Lanka bir sonraki yolculuğunuza ilham versin.",
    newsletterText: "Destinasyon hikâyeleri, mevsimsel fikirler ve gizli yer rehberleri alın.",
    emailPlaceholder: "E-posta adresiniz",
    subscribe: "Abone ol",
    footerText: "Sri Lanka'nın insanlarını, yerlerini ve deneyimlerini keşfetmek için premium bilgi merkezi.",
    explore: "Keşfet",
    destinations: "Destinasyonlar",
    experiences: "Deneyimler",
    interactiveMap: "Etkileşimli harita",
    travelInfo: "Seyahat bilgisi",
    weather: "Hava",
    transport: "Ulaşım",
    safety: "Güvenlik ve görgü",
    languages: "Diller",
    informationalOnly: "Bilgi platformu — doğrudan rezervasyon yok.",
    whatsappFrance: "WhatsApp Fransa",
    noResults: "Sonuç bulunamadı",
    openingWhatsApp: "WhatsApp açılıyor...",
    waToast: "WhatsApp talebinizle açılıyor",
    thanksSubscribe: "Teşekkürler! Yakında ilham göndereceğiz.",
    subSaved: "Abonelik kaydedildi",
    langName: "Türkçe",
  },
  de: {
    navDiscover: "Entdecken",
    navRegions: "Regionen",
    navExperiences: "Erlebnisse",
    navMap: "Karte",
    navGuide: "Reiseführer",
    navContact: "Kontakt",
    heroEyebrow: "Die Insel der tausend Reisen",
    heroTitleOne: "Entdecken Sie Sri Lanka,",
    heroTitleTwo: "jenseits des Gewöhnlichen.",
    heroText: "Erkunden Sie antike Städte, neblige Berge, wilde Küsten, heilige Orte und lokale Geschichten in einem schönen Reiseinformationszentrum.",
    searchButton: "Erkunden",
    searchPlaceholder: "Orte, Regionen oder Erlebnisse suchen...",
    popularLabel: "Beliebt:",
    wildlife: "Tierwelt",
    provinces: "Provinzen",
    heritage: "Erbe",
    introKicker: "Eine lebendige Insel",
    introTitle: "Ein Ziel.<br/><em>Endlose Geschichten.</em>",
    introText: "Von den antiken Königreichen des Kulturdreiecks bis zu teebedeckten Hügeln, tropischen Stränden und tierreichen Wäldern bietet Sri Lanka außergewöhnliche Vielfalt auf einer Insel.",
    exploreRegions: "Alle Regionen erkunden",
    featuredKicker: "Redaktionstipp",
    featuredTitle: "Orte, die die Reise wert sind",
    hillCountry: "Bergland",
    coastalHeritage: "Küstenerbe",
    wildNature: "Wilde Natur",
    sigiriyaDesc: "Antike Felsenfestung, königliche Gärten und unvergessliche Ausblicke.",
    ellaDesc: "Teepfade, Bergluft und eine der schönsten Bahnstrecken Asiens.",
    galleDesc: "Ozeanmauern, koloniale Straßen und zeitloser südlicher Charme.",
    yalaDesc: "Leoparden, Elefanten und dramatische Landschaften zwischen Wald und Meer.",
    regionsKicker: "Geografisch erkunden",
    regionsTitle: "Finden Sie Ihre Region",
    all: "Alle",
    culture: "Kultur",
    nature: "Natur",
    coast: "Küste",
    centralProvince: "Zentralprovinz",
    centralDesc: "Heiliges Kandy, neblige Hochländer und antike Höhlentempel.",
    southernProvince: "Südprovinz",
    southernDesc: "Historisches Galle, Surfstädte, Walgebiet und goldene Strände.",
    uvaProvince: "Uva-Provinz",
    uvaDesc: "Bergaussichten, Wasserfälle, Teeplantagen und ruhige Dörfer.",
    northCentralProvince: "Nord-Zentralprovinz",
    northCentralDesc: "Das Herz der antiken königlichen Zivilisation Sri Lankas.",
    easternProvince: "Ostprovinz",
    easternDesc: "Ruhige Buchten, Korallenmeere, Tempel und entspanntes Küstenleben.",
    sabaragamuwaProvince: "Sabaragamuwa-Provinz",
    sabaragamuwaDesc: "Regenwälder, heilige Gipfel, Flüsse und Sri Lankas Edelsteinland.",
    experienceKicker: "Reisen nach Gefühl",
    experienceTitle: "Wählen Sie das Erlebnis, das Sie ruft.",
    ancientHeritage: "Antikes Erbe",
    wildlifeSafaris: "Wildlife & Safaris",
    beaches: "Strände & Inseln",
    adventure: "Abenteuer & Outdoor",
    wellness: "Wellness & Ayurveda",
    food: "Essen & lokales Leben",
    mapKicker: "Visuell erkunden",
    mapTitle: "Sri Lanka auf einen Blick",
    mapText: "Wählen Sie eine Markierung, um Signaturziele der Insel zu entdecken.",
    guideKicker: "Vor der Reise wissen",
    guideTitle: "Praktisches Reisewissen, schön einfach.",
    weatherTitle: "Wetter & Jahreszeiten",
    weatherText: "Verstehen Sie die regionalen Monsune Sri Lankas und die besten Monate für jede Küste.",
    transportTitle: "Unterwegs",
    transportText: "Züge, Busse, Privattransport und realistische Reisezeiten.",
    cultureTitle: "Kultur & Etikette",
    cultureText: "Respektvoll reisen mit einfacher Orientierung für Tempel, Gemeinschaften und Bräuche.",
    readGuide: "Guide lesen →",
    contactKicker: "Kontakt",
    osReady: "Bereit für Travel OS",
    contactTitle: "Ihre Verbindung zu Sri Lanka, aus Frankreich.",
    contactIntro: "Für Informationen zu Zielen, Erlebnissen und touristischen Dienstleistungen in Sri Lanka kontaktieren Sie unser Team.",
    openWhatsApp: "WhatsApp Frankreich öffnen",
    addressTitle: "Adresse in Frankreich",
    whatsappPrimary: "Haupt-WhatsApp — Frankreich",
    phoneSriLanka: "Telefon / WhatsApp Sri Lanka",
    emailLabel: "E-Mail",
    websiteLabel: "Webseite",
    requestKicker: "Ihr Reiseprojekt",
    requestTitle: "Erzählen Sie uns von Ihrer nächsten Reise.",
    requestText: "Dieses Formular ist bereit für Ihr künftiges Travel OS. Derzeit öffnet es WhatsApp mit Ihrer Anfrage.",
    fullNameLabel: "Vollständiger Name",
    fullNamePlaceholder: "Ihr vollständiger Name",
    emailFormLabel: "E-Mail",
    emailFormPlaceholder: "ihre@email.com",
    whatsappFormLabel: "Telefon / WhatsApp",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "Reisedatum",
    travellersLabel: "Anzahl Reisende",
    interestLabel: "Haupterlebnis",
    interestTour: "Kulturreise",
    interestNature: "Natur & Tierwelt",
    interestBeach: "Strände",
    interestFamily: "Familienreise",
    interestCustom: "Maßgeschneiderte Reise",
    messageLabel: "Ihre Anfrage",
    messagePlaceholder: "Beschreiben Sie Ihre Reiseidee...",
    sendRequest: "Anfrage senden",
    newsletterKicker: "Geschichten von der Insel",
    newsletterTitle: "Lassen Sie Sri Lanka Ihre nächste Reise inspirieren.",
    newsletterText: "Erhalten Sie Zielgeschichten, saisonale Ideen und Guides zu versteckten Orten.",
    emailPlaceholder: "Ihre E-Mail-Adresse",
    subscribe: "Abonnieren",
    footerText: "Ein Premium-Informationszentrum für Menschen, Orte und Erlebnisse Sri Lankas.",
    explore: "Entdecken",
    destinations: "Ziele",
    experiences: "Erlebnisse",
    interactiveMap: "Interaktive Karte",
    travelInfo: "Reiseinfo",
    weather: "Wetter",
    transport: "Transport",
    safety: "Sicherheit & Etikette",
    languages: "Sprachen",
    informationalOnly: "Informationsplattform — keine Direktbuchung.",
    whatsappFrance: "WhatsApp Frankreich",
    noResults: "Keine Ergebnisse",
    openingWhatsApp: "WhatsApp wird geöffnet...",
    waToast: "WhatsApp öffnet sich mit Ihrer Anfrage",
    thanksSubscribe: "Danke! Wir senden bald Inspiration.",
    subSaved: "Abo gespeichert",
    langName: "Deutsch",
  },
  ar: {
    navDiscover: "اكتشف",
    navRegions: "المناطق",
    navExperiences: "التجارب",
    navMap: "الخريطة",
    navGuide: "دليل السفر",
    navContact: "اتصل بنا",
    heroEyebrow: "جزيرة ألف رحلة",
    heroTitleOne: "اكتشف سريلانكا،",
    heroTitleTwo: "أبعد من المألوف.",
    heroText: "استكشف المدن القديمة والجبال الضبابية والسواحل البرية والأماكن المقدسة والقصص المحلية عبر مركز معلومات سياحي جميل واحد.",
    searchButton: "استكشف",
    searchPlaceholder: "ابحث عن أماكن أو مناطق أو تجارب...",
    popularLabel: "شائع:",
    wildlife: "الحياة البرية",
    provinces: "المحافظات",
    heritage: "التراث",
    introKicker: "جزيرة حية",
    introTitle: "وجهة واحدة.<br/><em>قصص لا تنتهي.</em>",
    introText: "من الممالك القديمة في المثلث الثقافي إلى تلال الشاي والشواطئ الاستوائية والغابات الغنية بالحياة البرية، تقدم سريلانكا تنوعًا استثنائيًا في جزيرة واحدة.",
    exploreRegions: "استكشف كل المناطق",
    featuredKicker: "اختيار التحرير",
    featuredTitle: "أماكن تستحق الرحلة",
    hillCountry: "بلاد التلال",
    coastalHeritage: "تراث ساحلي",
    wildNature: "طبيعة برية",
    sigiriyaDesc: "قلعة صخرية قديمة وحدائق ملكية ومناظر لا تُنسى.",
    ellaDesc: "مسارات الشاي وهواء الجبال وواحدة من أجمل رحلات القطار في آسيا.",
    galleDesc: "أسوار المحيط وشوارع استعمارية وسحر جنوبي خالد.",
    yalaDesc: "فهود وفيلة ومناظر درامية بين الغابة والبحر.",
    regionsKicker: "استكشف جغرافيًا",
    regionsTitle: "اعثر على منطقتك",
    all: "الكل",
    culture: "ثقافة",
    nature: "طبيعة",
    coast: "ساحل",
    centralProvince: "المقاطعة الوسطى",
    centralDesc: "كاندي المقدسة والمرتفعات الضبابية ومعابد الكهوف القديمة.",
    southernProvince: "المقاطعة الجنوبية",
    southernDesc: "غالي التاريخية ومدن الأمواج وبلد الحيتان والشواطئ الذهبية.",
    uvaProvince: "مقاطعة أوفا",
    uvaDesc: "مناظر جبلية وشلالات ومزارع شاي وقرى هادئة.",
    northCentralProvince: "المقاطعة الشمالية الوسطى",
    northCentralDesc: "قلب الحضارة الملكية القديمة في سريلانكا.",
    easternProvince: "المقاطعة الشرقية",
    easternDesc: "خلجان هادئة وبحار مرجانية ومعابد وحياة ساحلية مريحة.",
    sabaragamuwaProvince: "مقاطعة سباراجاموا",
    sabaragamuwaDesc: "غابات مطيرة وقمم مقدسة وأنهار وبلد الجواهر.",
    experienceKicker: "سافر بالإحساس",
    experienceTitle: "اختر التجربة التي تناديك.",
    ancientHeritage: "تراث قديم",
    wildlifeSafaris: "الحياة البرية والسفاري",
    beaches: "شواطئ وجزر",
    adventure: "مغامرة وأنشطة خارجية",
    wellness: "العافية والآيورفيدا",
    food: "الطعام والحياة المحلية",
    mapKicker: "استكشف بصريًا",
    mapTitle: "سريلانكا في لمحة",
    mapText: "اختر علامة لاكتشاف الوجهات المميزة في الجزيرة.",
    guideKicker: "اعرف قبل أن تذهب",
    guideTitle: "معرفة سفر عملية، بسيطة وجميلة.",
    weatherTitle: "الطقس والفصول",
    weatherText: "افهم الرياح الموسمية الإقليمية في سريلانكا وأفضل الشهور لكل ساحل.",
    transportTitle: "التنقل",
    transportText: "قطارات وحافلات ونقل خاص وأوقات سفر واقعية.",
    cultureTitle: "الثقافة وآداب السلوك",
    cultureText: "سافر باحترام مع إرشادات بسيطة للمعابد والمجتمعات والعادات.",
    readGuide: "اقرأ الدليل ←",
    contactKicker: "تواصل معنا",
    osReady: "جاهز لـ Travel OS",
    contactTitle: "رابطك إلى سريلانكا من فرنسا.",
    contactIntro: "لأي معلومات عن الوجهات والتجارب وخدمات السياحة في سريلانكا، تواصل مع فريقنا.",
    openWhatsApp: "افتح واتساب فرنسا",
    addressTitle: "العنوان في فرنسا",
    whatsappPrimary: "واتساب الرئيسي — فرنسا",
    phoneSriLanka: "هاتف / واتساب سريلانكا",
    emailLabel: "البريد الإلكتروني",
    websiteLabel: "الموقع",
    requestKicker: "مشروع سفرك",
    requestTitle: "أخبرنا عن رحلتك القادمة.",
    requestText: "هذا النموذج جاهز للاتصال بـ Travel OS المستقبلي. حاليًا يفتح واتساب مع طلبك.",
    fullNameLabel: "الاسم الكامل",
    fullNamePlaceholder: "اسمك الكامل",
    emailFormLabel: "البريد الإلكتروني",
    emailFormPlaceholder: "your@email.com",
    whatsappFormLabel: "هاتف / واتساب",
    whatsappFormPlaceholder: "+33 ...",
    travelDateLabel: "تاريخ السفر",
    travellersLabel: "عدد المسافرين",
    interestLabel: "التجربة الرئيسية",
    interestTour: "جولة ثقافية",
    interestNature: "طبيعة وحياة برية",
    interestBeach: "شواطئ",
    interestFamily: "رحلة عائلية",
    interestCustom: "رحلة مخصصة",
    messageLabel: "طلبك",
    messagePlaceholder: "صف فكرة سفرك...",
    sendRequest: "أرسل الطلب",
    newsletterKicker: "قصص من الجزيرة",
    newsletterTitle: "دع سريلانكا تلهم رحلتك القادمة.",
    newsletterText: "استلم قصص الوجهات وأفكار السفر الموسمية وأدلة الأماكن المخفية.",
    emailPlaceholder: "بريدك الإلكتروني",
    subscribe: "اشترك",
    footerText: "مركز معلومات متميز لاكتشاف الناس والأماكن والتجارب في سريلانكا.",
    explore: "استكشف",
    destinations: "الوجهات",
    experiences: "التجارب",
    interactiveMap: "خريطة تفاعلية",
    travelInfo: "معلومات السفر",
    weather: "الطقس",
    transport: "النقل",
    safety: "السلامة والآداب",
    languages: "اللغات",
    informationalOnly: "منصة معلومات سياحية — بدون حجز مباشر.",
    whatsappFrance: "واتساب فرنسا",
    noResults: "لا توجد نتائج",
    openingWhatsApp: "جاري فتح واتساب...",
    waToast: "واتساب يفتح مع طلبك",
    thanksSubscribe: "شكرًا! سنرسل الإلهام قريبًا.",
    subSaved: "تم حفظ الاشتراك",
    langName: "العربية",
  },
};

window.CE_LANG_META = {
  en: { code: "EN", name: "English", dir: "ltr" },
  fr: { code: "FR", name: "Français", dir: "ltr" },
  ru: { code: "RU", name: "Русский", dir: "ltr" },
  tr: { code: "TR", name: "Türkçe", dir: "ltr" },
  de: { code: "DE", name: "Deutsch", dir: "ltr" },
  ar: { code: "AR", name: "العربية", dir: "rtl" }
};
